

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shinobi-data
  namespace: shinobi
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
